docker:
  context: default
  identifier: demo

environment:
  files:
    - global.env

applications:
  website:
    root: ./website
    files:
      - docker-compose.yaml
    project:
      name: website
    environment:
      files:
        - vars.env

volumes:
  demo-volume-1:

networks:
  demo-network: