docker:
  context: default
  identifier: demo

environment:
  files:
    - global.env
  inline:
    - GFOO=bar
    - GBAZ=qux

applications:
  website:
    root: website
    files:
      - docker-compose.yaml
    project:
      name: website
    environment:
      files:
        - vars.env
      inline:
        - FOO=bar
        - BAZ=qux

volumes:
  demo-volume-1:

networks:
  demo-network: