docker:
  context: default
  identifier: demo

sops:
  age:
    key_file: ~/.config/sops/age/keys.txt

secrets:
  sops:
    - path: secrets.env
      format: dotenv # dotenv | yaml | json

environment:
  files:
    - global.env
  inline:
    - GFOO=bar
    - GBAZ=qux

applications:
  website:
    root: website
    files:
      - docker-compose.yaml
    project:
      name: website
    environment:
      files:
        - vars.env
      inline:
        - FOO=bar
        - BAZ=qux
    secrets:
      sops:
        - path: secrets.env
          format: dotenv

volumes:
  demo-volume-1:

networks:
  demo-network: