version: "2"

run:
  timeout: 5m

# Note: v2 schema rejects v1-era issues.* keys like exclude-use-default/exclude-rules.
# Keep config minimal and valid; add specific rules later with v2-compatible keys.
