run:
  timeout: 5m

issues:
  # Disable default exclusions to match CI behavior
  # This ensures local linting catches the same issues as CI
  exclude-use-default: false
  
  # Exclude some linters from test files
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - goconst
