name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '*.svg'
      - '*.png'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - 'README.md'
      - '*.svg'
      - '*.png'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=5m
  test:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Setup SOPS
        uses: nhedger/setup-sops@v2
        with:
          version: "latest"

      - name: Create dummy age key file (Linux)
        if: runner.os == 'Linux'
        run: |
          mkdir -p /home/runner/.config/sops/age
          echo 'AGE-SECRET-KEY-1XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' > /home/runner/.config/sops/age/keys.txt

      - name: Create dummy age key file (Windows)
        if: runner.os == 'Windows'
        run: |
          New-Item -ItemType Directory -Force -Path "$env:APPDATA\sops\age"
          Set-Content -Path "$env:APPDATA\sops\age\keys.txt" -Value 'AGE-SECRET-KEY-1XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test ./internal/... -v
  e2e:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Setup SOPS
        uses: nhedger/setup-sops@v2
        with:
          version: "latest"

      - name: Setup Age
        uses: alessiodionisi/setup-age-action@v1.3.0

      - name: Run e2e tests
        run: go test ./test/e2e -v